function [A,B] = stateJacobianFcnBase(in1,in2)
%stateJacobianFcnBase
%    [A,B] = stateJacobianFcnBase(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Oct-2024 18:52:48

phi = in1(1,:);
v = in2(1,:);
t2 = cos(phi);
t3 = sin(phi);
A = reshape([0.0,-t3.*v,t2.*v,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
if nargout > 1
    B = reshape([0.0,t2,t3,1.0,0.0,0.0],[3,2]);
end
end
